name: EcoRoute AI CI Pipeline

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main]

# এখানে আমরা গিটহাব রানারকে জোর করে Node 24 ব্যবহার করতে বলছি যাতে ওয়ার্নিং উধাও হয়ে যায়
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "24" # নোড ২০ কেটে ২৪ করে দেওয়া হলো
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run Build
        run: npm run build
      - name: Run Tests
        run: npm test
